from __future__ import annotations

from datetime import timedelta

from django.db import models
from django.db.models import Manager
from django.utils import timezone

from aso.scoring import (
    calc_opportunity,
    classify_keyword,
    difficulty_color,
    difficulty_label,
    get_targeting_advice,
    opportunity_reach,
)


class App(models.Model):
    """
    Represents one of the user's iOS apps.

    Used for organizing keywords into groups — each keyword can
    optionally be associated with an app.

    When added via App Store lookup, track_id stores the iTunes
    numeric ID so we can find the app's rank in search results.
    """

    id: int  # Auto-generated by Django, declared for type checkers
    keywords: Manager[Keyword]

    name = models.CharField(max_length=200)
    bundle_id = models.CharField(
        max_length=200,
        blank=True,
        default="",
        help_text="e.g., com.example.myapp",
    )
    track_id = models.BigIntegerField(
        null=True,
        blank=True,
        unique=True,
        help_text="iTunes trackId — used for rank tracking in search results",
    )
    store_url = models.URLField(
        blank=True,
        default="",
        help_text="App Store URL",
    )
    store_profiles = models.JSONField(
        default=dict,
        blank=True,
        help_text=(
            "What the App Store shows for this app in each storefront, as "
            "last read: {code: {count, average, released, checked_at}}. "
            "Written only by aso/app_profiles.py; the opportunity score reads it."
        ),
    )
    icon_url = models.URLField(
        blank=True,
        default="",
        help_text="App icon URL from iTunes",
    )
    seller_name = models.CharField(
        max_length=200,
        blank=True,
        default="",
        help_text="Developer/publisher name",
    )
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name


class Keyword(models.Model):
    """
    A keyword being tracked for ASO research.

    Can optionally be linked to an App for categorization.
    """

    id: int  # Auto-generated by Django, declared for type checkers
    results: Manager[SearchResult]

    keyword = models.CharField(max_length=200)
    app = models.ForeignKey(
        App,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="keywords",
    )
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ("keyword", "app")
        ordering = ["-created_at"]

    def __str__(self):
        if self.app:
            return f"{self.keyword} ({self.app.name})"
        return self.keyword


class SearchResult(models.Model):
    """
    Stores the result of a keyword search at a point in time.

    Contains popularity score (from Apple), difficulty score (calculated),
    and the raw competitor data from iTunes Search API.
    """

    id: int  # Auto-generated by Django, declared for type checkers

    keyword = models.ForeignKey(
        Keyword,
        on_delete=models.CASCADE,
        related_name="results",
    )
    popularity_score = models.IntegerField(
        null=True,
        blank=True,
        help_text=(
            "RespectASO's estimate (1-100, calibrated to Apple's official "
            "popularity scale - estimate v2)."
        ),
    )
    apple_popularity_score = models.IntegerField(
        null=True,
        blank=True,
        help_text=(
            "Apple's official searchPopularity1to100 at snapshot time "
            "(null when the keyword was not among Apple's top terms)."
        ),
    )
    difficulty_score = models.IntegerField(
        help_text="1-100 calculated difficulty score",
    )
    difficulty_breakdown = models.JSONField(
        default=dict,
        help_text="Component scores breakdown",
    )
    competitors_data = models.JSONField(
        default=list,
        help_text="Array of top competitor app dicts from iTunes",
    )
    app_rank = models.IntegerField(
        null=True,
        blank=True,
        help_text="App's 1-indexed rank in top-200 iTunes results (null if not found)",
    )
    country = models.CharField(
        max_length=5,
        default="us",
        help_text="Country code used for this search",
    )
    inferred_genre = models.CharField(
        max_length=100,
        blank=True,
        default="",
        help_text=(
            "Apple genre bucket inferred from this snapshot's competitors "
            "(aso.apple_ads.genres). Drives the genre-aware fallback cap "
            "under the Apple source; empty = uninferred (global floor)."
        ),
    )
    classification = models.CharField(
        max_length=20,
        default="Low Volume",
        help_text="Keyword classification label from classify_keyword()",
    )
    searched_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["-searched_at"]

    def __str__(self):
        return f"{self.keyword.keyword} — {self.searched_at:%Y-%m-%d %H:%M}"

    @classmethod
    def upsert_today(cls, keyword, country, **fields):
        """
        Create or replace today's result for a keyword+country pair.

        If a result already exists for today, delete it and create a fresh one.
        This ensures exactly one data point per keyword per country per day.
        """
        today_start = timezone.now().replace(hour=0, minute=0, second=0, microsecond=0)
        today_end = today_start + timedelta(days=1)
        cls.objects.filter(
            keyword=keyword,
            country=country,
            searched_at__gte=today_start,
            searched_at__lt=today_end,
        ).delete()
        return cls.objects.create(keyword=keyword, country=country, **fields)

    def save(self, *args, **kwargs):
        """Auto-compute classification from the effective popularity on save,
        for the app this keyword is tracked for."""
        self.classification = classify_keyword(
            self.effective_popularity or 0, self.difficulty_score, self.country,
            app=self.app_profile, app_rank=self.app_rank, keyword=self.keyword_text,
        )
        super().save(*args, **kwargs)

    @property
    def app(self):
        """The app this row is scored for: its keyword's app, or None."""
        return self.keyword.app if self.keyword_id else None

    @property
    def app_profile(self):
        """The app's profile in this storefront, as last read (an AppProfile);
        None for a keyword without an app. An app not yet read here scores
        as a brand new app, and the screen says so."""
        from .app_profiles import cached_profile

        return cached_profile(self.app, self.country)

    def _resolve_popularity_pair(self):
        """(effective, source, is_fallback) per the user's source selection."""
        from .popularity import (
            SOURCE_APPLE,
            absent_cap,
            effective_from_pair,
            get_popularity_source,
        )

        source_setting = get_popularity_source()
        ceiling = (
            absent_cap(self.country, self.inferred_genre)
            if source_setting == SOURCE_APPLE else None
        )
        return effective_from_pair(
            self.popularity_score,
            self.apple_popularity_score,
            source_setting,
            absent_ceiling=ceiling,
        )

    def popularity_resolution(self):
        """Both popularity sources and their provenance, resolved once.

        The same ``PopularityResolution`` live scoring produces, rebuilt from
        the stored values, so ``popularity_fields()`` renders a stored row
        exactly like a fresh one (one lookup instead of one per property).
        """
        from .popularity import resolution_from_stored

        return resolution_from_stored(
            self.popularity_score, self.apple_popularity_score,
            self.country, self.inferred_genre,
        )

    @property
    def effective_popularity(self):
        """The popularity value that feeds all calculations for this row."""
        return self._resolve_popularity_pair()[0]

    @property
    def popularity_source_used(self):
        """"internal" or "apple" — the source of effective_popularity."""
        return self._resolve_popularity_pair()[1]

    @property
    def popularity_is_fallback(self):
        """True when Apple is selected but this row has no Apple value."""
        return self._resolve_popularity_pair()[2]

    @property
    def keyword_text(self) -> str:
        """The keyword as text. OpportunityScanResult stores it as a column,
        so one payload builder serves both row models, and the scores read it:
        when the app's title already carries it, the real rank is final."""
        return self.keyword.keyword if self.keyword_id else ""

    @property
    def difficulty_label(self):
        """Human-readable difficulty interpretation."""
        return difficulty_label(self.difficulty_score)

    @property
    def difficulty_color(self):
        """Tailwind color class for the difficulty score."""
        return difficulty_color(self.difficulty_score)


    @property
    def opportunity_score(self):
        """Computed opportunity score from the effective popularity.

        The storefront matters: a market with almost no searches cannot carry
        an opportunity however weak its competitors look.
        """
        return calc_opportunity(
            self.effective_popularity or 0, self.difficulty_score, self.country,
            app=self.app_profile, app_rank=self.app_rank, keyword=self.keyword_text,
        )

    @property
    def opportunity_reach(self) -> dict:
        """Where this row's app would rank, what that pays, and why.

        The table prints the short line under the score and the explanation
        behind it, so the score arrives with its working shown. Same inputs
        as opportunity_score, so the two cannot disagree.
        """
        return opportunity_reach(
            self.effective_popularity or 0, self.difficulty_score, self.country,
            app=self.app_profile, app_rank=self.app_rank, keyword=self.keyword_text,
        )

    @property
    def targeting_advice(self):
        """Return (icon, label, css_classes, description) for ASO targeting.

        The storefront goes in too: the advice describes search volume, and
        volume is popularity times market size. Without it a row could show
        "Under 1 search a day" and "high search volume" side by side.
        """
        return get_targeting_advice(
            self.effective_popularity, self.difficulty_score, self.country,
            app=self.app_profile, app_rank=self.app_rank, keyword=self.keyword_text,
        )

    @property
    def effective_download_estimates(self):
        """Download estimates recomputed from the EFFECTIVE popularity.

        The snapshot stored in difficulty_breakdown was computed with the
        popularity source active at scoring time; recomputing at read time
        (DownloadEstimator is pure, deterministic math) keeps the downloads
        column consistent with the popularity column after a source switch.
        Returns None when this row has no popularity at all.
        """
        effective = self.effective_popularity
        if effective is None:
            return None
        from .services import DownloadEstimator

        return DownloadEstimator().estimate(effective, country=self.country)



class KeywordSearchJob(models.Model):
    """One keyword search from the Keyword Research tab, as a persistent job.

    The list of keywords and countries is the work; ``next_index`` is the
    cursor into it (pair order is keyword-major: pair ``i`` is keyword
    ``i // n_countries`` in country ``i % n_countries``, so "214 of 1,000
    keywords done" is literally true and a resumed job continues with the
    next keyword). The run queue (aso/run_queue.py) executes one job at a
    time; a job survives quitting the app, a crash and a container restart
    because everything it needs is in this row.

    Statuses: queued (waiting its turn), running, paused (by the user, by a
    throttle, after an error, or to let another run go first), completed,
    failed (the dispatcher's backstop; treated like paused after an error),
    cancelled (the user discarded the rest). Nothing is ever discarded by
    the system.
    """

    STATUS_CHOICES = [
        ("queued", "Queued"),
        ("running", "Running"),
        ("paused", "Paused"),
        ("completed", "Completed"),
        ("failed", "Failed"),
        ("cancelled", "Cancelled"),   # the user discarded the rest
    ]
    ACTIVE_STATUSES = ("queued", "running", "paused", "failed")
    TERMINAL_STATUSES = ("completed", "cancelled")
    THROTTLE_CHOICES = [
        ("normal", "Normal"),
        ("slowed_down", "Slowed down"),
        ("paused", "Paused by throttling"),
        ("cooldown", "Cooling down"),
    ]

    app = models.ForeignKey(
        App, on_delete=models.SET_NULL, null=True, blank=True, related_name="search_jobs",
    )
    countries = models.JSONField(default=list)     # ["us", "de"], validated, max 5, order kept
    keywords = models.JSONField(default=list)      # parsed list, original spelling, deduped, order kept
    status = models.CharField(max_length=12, choices=STATUS_CHOICES, default="queued")
    queue_rank = models.IntegerField(null=True, blank=True)   # queue order; NULL = append
    # Paused so another run could go first; restored to the front of the
    # queue by the dispatcher once that run is done.
    auto_resume = models.BooleanField(default=False)
    yielded_for_feature = models.CharField(max_length=32, blank=True, default="")
    yielded_for_id = models.IntegerField(null=True, blank=True)
    yielded_for_label = models.CharField(max_length=220, blank=True, default="")
    next_index = models.PositiveIntegerField(default=0)   # pair index of the next unit of work
    done_count = models.PositiveIntegerField(default=0)
    skipped_count = models.PositiveIntegerField(default=0)
    failed_count = models.PositiveIntegerField(default=0)
    skipped_items = models.JSONField(default=list)   # ["invoice maker (US)", ...]
    failed_items = models.JSONField(default=list)    # [{"keyword", "country", "error"}], capped
    current_pair = models.CharField(max_length=220, blank=True, default="")   # 'meditation timer (DE)'
    progress_message = models.CharField(max_length=200, blank=True, default="")
    error_message = models.TextField(blank=True, default="")
    throttle_state = models.CharField(max_length=16, choices=THROTTLE_CHOICES, default="normal")
    seconds_per_pair = models.FloatField(null=True, blank=True)   # running average, feeds the ETA
    elapsed_seconds = models.FloatField(default=0)                # active time across resumes
    acknowledged = models.BooleanField(default=False)             # "Close" pressed on a finished job
    restart_resumes = models.PositiveIntegerField(default=0)      # continued after the app was closed mid-run
    created_at = models.DateTimeField(auto_now_add=True)
    started_at = models.DateTimeField(null=True, blank=True)
    finished_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        ordering = ["-created_at"]

    def __str__(self):
        return f"{self.total_keywords} keywords ({', '.join(c.upper() for c in self.countries)}) - {self.status}"

    @property
    def total_keywords(self) -> int:
        return len(self.keywords or [])

    @property
    def total_pairs(self) -> int:
        return len(self.keywords or []) * len(self.countries or [])

    @property
    def keywords_done(self) -> int:
        """Keywords fully worked through (every country), from the cursor."""
        n = len(self.countries or [])
        return self.next_index // n if n else 0

    @property
    def remaining_keywords(self) -> list:
        """The keywords not finished yet, in order - what Copy copies."""
        return list((self.keywords or [])[self.keywords_done:])

    @property
    def remaining_count(self) -> int:
        return self.total_keywords - self.keywords_done

    @property
    def progress_percent(self) -> int:
        total = self.total_pairs
        return int(self.next_index * 100 / total) if total else 0

    @property
    def is_active(self) -> bool:
        return self.status in self.ACTIVE_STATUSES

    @property
    def is_terminal(self) -> bool:
        return self.status in self.TERMINAL_STATUSES

    def pair(self, index):
        """(keyword, country) for pair ``index``."""
        n = len(self.countries)
        return self.keywords[index // n], self.countries[index % n]


class AppleSearchPopularity(models.Model):
    """
    Local lookup table of the CURRENT Apple popularity value per keyword.

    Populated by aso.apple_ads.sync from the active week of the official
    Apple Ads top-search-terms dataset (AppleTopTerm). One row per
    (term, country), refreshed at each weekly ingest and materialized on
    demand for newly scored keywords. Scoring reads this table only
    (never the network).

    popularity is null when the term is absent from Apple's dataset for
    that storefront (below Apple's reporting threshold of roughly 500
    weekly searches) - stored explicitly so resolution knows the absence
    is definitive for the active week.
    """

    id: int  # Auto-generated by Django, declared for type checkers

    term = models.CharField(
        max_length=200,
        help_text="Normalized keyword (lower().strip()).",
    )
    country = models.CharField(
        max_length=5,
        help_text="Storefront country code, lowercase (e.g. 'us').",
    )
    popularity = models.IntegerField(
        null=True,
        blank=True,
        help_text=(
            "Apple searchPopularity1to100 (observed floor ~40); null = "
            "absent from Apple's top search terms for this storefront."
        ),
    )
    fetched_at = models.DateTimeField(auto_now=True)

    class Meta:
        unique_together = ("term", "country")
        indexes = [models.Index(fields=["term", "country"])]
        verbose_name_plural = "Apple search popularities"

    def __str__(self):
        return f"{self.term} ({self.country}) — {self.popularity}"

    @classmethod
    def lookup(cls, term, country):
        """Return the Apple popularity for a normalized term, or None."""
        return (
            cls.objects.filter(term=term, country=country)
            .values_list("popularity", flat=True)
            .first()
        )

    @classmethod
    def bulk_lookup(cls, terms, country):
        """Return {term: popularity} for the given normalized terms (one query).

        Terms Apple has no row for are absent; terms with a null value map
        to None (both resolve to the internal fallback downstream).
        """
        rows = cls.objects.filter(term__in=list(terms), country=country)
        return dict(rows.values_list("term", "popularity"))


class AppleTopTerm(models.Model):
    """
    One row of Apple's official weekly top-search-terms dataset.

    Populated by aso.apple_ads.sync from the Apple Ads Platform API v1
    search-term-popularity endpoint: per storefront and completed
    Sun-Sat week, the top (up to) 500 terms in each of Apple's 15 broad
    genres. Every term appears in exactly one genre per country-week
    (verified live), so (term, country, week) is effectively unique too.

    Retention: the full dataset is kept for recent weeks; older weeks keep
    only rows matching tracked keywords (see sync.prune_top_terms).
    """

    id: int  # Auto-generated by Django, declared for type checkers

    term = models.CharField(
        max_length=200,
        help_text="Normalized search term (lower().strip()).",
    )
    country = models.CharField(
        max_length=5,
        help_text="Storefront country code, lowercase (e.g. 'us').",
    )
    genre = models.CharField(
        max_length=100,
        help_text="Apple genre value as returned by the API (e.g. 'BUSINESS').",
    )
    week = models.DateField(
        help_text="Sunday starting the Sun-Sat week this snapshot covers.",
    )
    rank_in_genre = models.IntegerField(
        help_text="Rank by search volume within country+genre (1 = highest).",
    )
    popularity_in_genre = models.SmallIntegerField(
        help_text="1-100 popularity within the genre for this storefront.",
    )
    popularity = models.SmallIntegerField(
        help_text=(
            "searchPopularity1to100: 1-100 across all genres in the "
            "storefront (observed floor ~40). Feeds scoring."
        ),
    )
    popularity_tier = models.SmallIntegerField(
        help_text="1-5 scale matching the Apple Ads Campaign Management UI.",
    )
    fetched_at = models.DateTimeField(default=timezone.now)

    class Meta:
        unique_together = ("term", "country", "genre", "week")
        indexes = [
            models.Index(fields=["country", "week"]),
            models.Index(fields=["term", "country", "week"]),
            models.Index(fields=["country", "genre", "week", "rank_in_genre"]),
        ]

    def __str__(self):
        return f"{self.term} ({self.country}, {self.week}) - {self.popularity}"

    @classmethod
    def latest_ingested_week(cls, country):
        """Newest week with rows for this country, or None."""
        return (
            cls.objects.filter(country=country)
            .order_by("-week")
            .values_list("week", flat=True)
            .first()
        )

    @classmethod
    def values_for_week(cls, terms, country, week):
        """{term: popularity} for the given normalized terms in one week.

        Terms absent from the dataset are absent from the dict (below
        Apple's reporting threshold for that storefront and week).
        """
        rows = cls.objects.filter(
            term__in=list(terms), country=country, week=week
        ).values_list("term", "popularity")
        values = {}
        for term, popularity in rows:
            if term not in values or popularity > values[term]:
                values[term] = popularity
        return values

    @classmethod
    def genre_floor(cls, country, week, genre=None):
        """Lowest reported market-wide popularity for a genre (or all).

        A keyword ABSENT from the dataset is only provably less popular
        than its own category's least-reported term - and category
        floors differ a lot (US week of 2026-08-09: SPORTS 40 ...
        GAMES 56). genre=None returns the country's global floor (the
        most conservative bound, used when the category is uninferred).
        Returns None when the week has no data. Cached per
        (country, week, genre) for the process lifetime.
        """
        from django.db.models import Min

        key = (country, week, genre)
        if key in _floor_cache:
            return _floor_cache[key]
        qs = cls.objects.filter(country=country, week=week)
        if genre:
            qs = qs.filter(genre=genre)
        floor = qs.aggregate(f=Min("popularity"))["f"]
        if floor is None and genre:
            # Unknown genre value: fall back to the global floor.
            floor = cls.genre_floor(country, week, None)
        _floor_cache[key] = floor
        return floor

    @classmethod
    def clear_floor_cache(cls):
        """Drop cached genre floors - call on week (re)activation and in
        tests that reseed dataset weeks."""
        _floor_cache.clear()

    @classmethod
    def trend_lookup(cls, terms, country, week):
        """{term: delta} of market-wide popularity vs the previous week.

        Only terms present in BOTH weeks get a delta (a term entering or
        leaving the dataset is a coverage change, not a measured trend).
        """
        from datetime import timedelta

        prev_week = week - timedelta(days=7)
        current = cls.values_for_week(terms, country, week)
        previous = cls.values_for_week(terms, country, prev_week)
        return {
            term: current[term] - previous[term]
            for term in current
            if term in previous
        }

    @classmethod
    def movers(cls, country, week, genre=None, limit=8):
        """Biggest rank climbers and fallers vs the previous week.

        Returns (risers, fallers): lists of dicts with term, genre, rank,
        prev_rank, rank_delta (positive = climbed), popularity, tier.
        Empty lists when the previous week is not ingested.
        """
        from datetime import timedelta

        prev_week = week - timedelta(days=7)
        current_qs = cls.objects.filter(country=country, week=week)
        prev_qs = cls.objects.filter(country=country, week=prev_week)
        if genre:
            current_qs = current_qs.filter(genre=genre)
            prev_qs = prev_qs.filter(genre=genre)
        previous = {
            (term, g): rank
            for term, g, rank in prev_qs.values_list(
                "term", "genre", "rank_in_genre"
            )
        }
        if not previous:
            return [], []
        deltas = []
        for row in current_qs.values(
            "term", "genre", "rank_in_genre", "popularity", "popularity_tier"
        ):
            prev_rank = previous.get((row["term"], row["genre"]))
            if prev_rank is None:
                continue
            delta = prev_rank - row["rank_in_genre"]  # positive = climbed
            if delta:
                deltas.append({
                    "term": row["term"],
                    "genre": row["genre"],
                    "rank": row["rank_in_genre"],
                    "prev_rank": prev_rank,
                    "rank_delta": delta,
                    "popularity": row["popularity"],
                    "tier": row["popularity_tier"],
                })
        deltas.sort(key=lambda d: -d["rank_delta"])
        risers = [d for d in deltas if d["rank_delta"] > 0][:limit]
        fallers = list(reversed([d for d in deltas if d["rank_delta"] < 0][-limit:]))
        return risers, fallers


_floor_cache: dict = {}


class AppleImpressionShare(models.Model):
    """
    Weekly impression-share rows for a tracked app's own ads.

    Populated by aso.apple_ads.impressions from the Apple Ads Platform
    API v1 impression-share endpoint. Apple only reports search terms
    where the app's ads actually served (and suppresses terms with fewer
    than 10 impressions), so most installs have no rows - the UI renders
    the section only when data exists.
    """

    id: int  # Auto-generated by Django, declared for type checkers

    app = models.ForeignKey(
        "App",
        on_delete=models.CASCADE,
        related_name="impression_shares",
    )
    country = models.CharField(
        max_length=5,
        help_text="Storefront country code, lowercase.",
    )
    search_term = models.CharField(
        max_length=200,
        help_text="Normalized search term the ads served on.",
    )
    week = models.DateField(
        help_text="Sunday starting the Sun-Sat week this row covers.",
    )
    low_share = models.FloatField(
        help_text=(
            "Lower bound of impression share, 0..1. Apple reports exact "
            "single-digit values between 1-90% and the band 91-100%."
        ),
    )
    high_share = models.FloatField(
        help_text="Upper bound of impression share, 0..1.",
    )
    rank = models.IntegerField(
        null=True,
        blank=True,
        help_text="App's impression-share rank on the term (1 = highest).",
    )
    popularity_tier = models.SmallIntegerField(
        null=True,
        blank=True,
        help_text="Apple's 1-5 search popularity for the term.",
    )
    fetched_at = models.DateTimeField(default=timezone.now)

    class Meta:
        unique_together = ("app", "country", "search_term", "week")
        indexes = [models.Index(fields=["app", "week"])]

    def __str__(self):
        return (
            f"{self.search_term} ({self.country}, {self.week}) - "
            f"{self.low_share:.0%}-{self.high_share:.0%}"
        )


class OpportunityScan(models.Model):
    """One Country Opportunity Finder scan, as a persistent job.

    A scan is one keyword across the storefronts the user picked, and it is a
    row rather than a loop in the browser: the scan survives navigating away,
    quitting the app and a crash, because everything it needs is here. The run
    queue (``aso/run_queue.py``) executes it one country at a time and stops at
    the next country boundary whenever the status is no longer "running", which
    is how Pause, Discard and Run now all work.

    It is a separate model from ``KeywordSearchJob`` on purpose. That job's
    cursor is keyword-major over keywords times countries, it skips pairs
    already scored today, and its whole premise is that results land in
    ``SearchResult`` immediately. A scan has one keyword, never skips, and
    deliberately keeps its results out of the search history until the user
    saves them. Sharing the table would have meant retrofitting a discriminator
    onto every query in aso/search_jobs.py and aso/views.py, where one missed
    filter shows a country scan in the dashboard's keyword panel.

    Results live in ``OpportunityScanResult``, one row per country. Old scans
    are pruned to the ten most recent on every create.
    """

    STATUS_CHOICES = [
        ("queued", "Queued"),
        ("running", "Running"),
        ("paused", "Paused"),
        ("completed", "Completed"),
        ("failed", "Failed"),
        ("cancelled", "Cancelled"),
    ]
    ACTIVE_STATUSES = ("queued", "running", "paused", "failed")
    TERMINAL_STATUSES = ("completed", "cancelled")
    THROTTLE_CHOICES = [
        ("normal", "Normal"),
        ("slowed_down", "Slowed down"),
        ("paused", "Paused by throttling"),
        ("cooldown", "Cooling down"),
    ]
    ORIGIN_CHOICES = [("web", "Web"), ("mcp", "MCP")]

    keyword = models.CharField(max_length=200)
    app = models.ForeignKey(
        App, on_delete=models.SET_NULL, null=True, blank=True,
        related_name="opportunity_scans",
    )
    countries = models.JSONField(default=list)   # the work list, order kept, no cap
    status = models.CharField(max_length=12, choices=STATUS_CHOICES, default="queued")
    queue_rank = models.IntegerField(null=True, blank=True)
    # Paused so another run could go first; restored to the front of the queue
    # by the dispatcher once that run is done.
    auto_resume = models.BooleanField(default=False)
    yielded_for_feature = models.CharField(max_length=32, blank=True, default="")
    yielded_for_id = models.IntegerField(null=True, blank=True)
    yielded_for_label = models.CharField(max_length=220, blank=True, default="")
    next_index = models.PositiveIntegerField(default=0)   # index into countries
    done_count = models.PositiveIntegerField(default=0)
    failed_count = models.PositiveIntegerField(default=0)
    failed_items = models.JSONField(default=list)   # [{"country", "error"}], capped
    current_country = models.CharField(max_length=5, blank=True, default="")
    progress_message = models.CharField(max_length=200, blank=True, default="")
    error_message = models.TextField(blank=True, default="")
    throttle_state = models.CharField(max_length=16, choices=THROTTLE_CHOICES, default="normal")
    seconds_per_country = models.FloatField(null=True, blank=True)   # feeds the ETA
    elapsed_seconds = models.FloatField(default=0)
    # Stamped on every country. A scan started from MCP runs in another
    # process, so a dead process is recognised by a stale heartbeat instead of
    # holding the single run lane for ever.
    heartbeat_at = models.DateTimeField(null=True, blank=True)
    acknowledged = models.BooleanField(default=False)
    restart_resumes = models.PositiveIntegerField(default=0)
    saved_count = models.PositiveIntegerField(default=0)   # rows sent to Search History
    origin = models.CharField(max_length=4, choices=ORIGIN_CHOICES, default="web")
    created_at = models.DateTimeField(auto_now_add=True)
    started_at = models.DateTimeField(null=True, blank=True)
    finished_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        ordering = ["-created_at"]

    def __str__(self):
        return f"{self.keyword} across {self.total_countries} countries - {self.status}"

    @property
    def total_countries(self) -> int:
        return len(self.countries or [])

    @property
    def remaining_count(self) -> int:
        return max(0, self.total_countries - self.next_index)

    @property
    def progress_percent(self) -> int:
        total = self.total_countries
        if not total:
            return 0
        return min(100, round(self.next_index / total * 100))

    @property
    def is_active(self) -> bool:
        return self.status in self.ACTIVE_STATUSES

    @property
    def is_terminal(self) -> bool:
        return self.status in self.TERMINAL_STATUSES

    def country_at(self, index: int) -> str:
        codes = self.countries or []
        return codes[index] if 0 <= index < len(codes) else ""


class OpportunityScanResult(models.Model):
    """One country's result inside a scan.

    Never a ``SearchResult``: the Country Opportunity Finder deliberately keeps
    its results out of the search history until the user picks the rows worth
    keeping, and Save copies them over with ``SearchResult.upsert_today``.

    Both popularity values are stored raw and resolved at read time, exactly
    like ``SearchResult``, so switching the popularity source re-reads an old
    scan correctly. Nothing derived is stored: the effective popularity, the
    opportunity, the classification and the difficulty label all come from
    ``popularity.resolution_from_stored`` and ``aso/scoring.py`` on the way out.
    """

    scan = models.ForeignKey(
        OpportunityScan, on_delete=models.CASCADE, related_name="results",
    )
    country = models.CharField(max_length=5)
    order_index = models.PositiveIntegerField()   # position in scan.countries
    keyword_text = models.CharField(max_length=200)
    popularity_score = models.IntegerField(null=True, blank=True)        # RespectASO estimate
    apple_popularity_score = models.IntegerField(null=True, blank=True)  # Apple's own value
    inferred_genre = models.CharField(max_length=80, blank=True, default="")
    difficulty_score = models.IntegerField(default=0)
    app_rank = models.IntegerField(null=True, blank=True)
    competitor_count = models.PositiveIntegerField(default=0)
    top_competitor = models.CharField(max_length=255, blank=True, default="")
    top_ratings = models.PositiveIntegerField(default=0)
    # The two heavy columns, read only when a row is expanded.
    difficulty_breakdown = models.JSONField(default=dict)
    competitors_data = models.JSONField(default=list)
    scanned_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ("scan", "country")
        ordering = ["order_index"]
        indexes = [models.Index(fields=["scan", "order_index"])]

    def __str__(self):
        return f"{self.keyword_text} ({self.country.upper()})"

    def popularity_resolution(self):
        """Both sources and their provenance, the same way SearchResult does."""
        from .popularity import resolution_from_stored

        return resolution_from_stored(
            self.popularity_score, self.apple_popularity_score,
            self.country, self.inferred_genre,
        )

    @property
    def effective_popularity(self):
        return self.popularity_resolution().effective

    @property
    def difficulty_label(self):
        return difficulty_label(self.difficulty_score)

    @property
    def difficulty_color(self):
        return difficulty_color(self.difficulty_score)

    @property
    def app(self):
        """The app the scan is for, or None."""
        return self.scan.app if self.scan_id else None

    @property
    def app_profile(self):
        """The scan's app, its profile in this storefront."""
        from .app_profiles import cached_profile

        return cached_profile(self.app, self.country)

    @property
    def opportunity_score(self) -> int:
        return calc_opportunity(
            self.effective_popularity or 0, self.difficulty_score, self.country,
            app=self.app_profile, app_rank=self.app_rank, keyword=self.keyword_text,
        )

    @property
    def classification(self) -> str:
        return classify_keyword(
            self.effective_popularity or 0, self.difficulty_score, self.country,
            app=self.app_profile, app_rank=self.app_rank, keyword=self.keyword_text,
        )

    @property
    def opportunity_reach(self) -> dict:
        """Where the scan's app (or a new app) lands here, what that pays and
        why: the same inputs as opportunity_score, as SearchResult has it."""
        return opportunity_reach(
            self.effective_popularity or 0, self.difficulty_score, self.country,
            app=self.app_profile, app_rank=self.app_rank, keyword=self.keyword_text,
        )
