from __future__ import annotations

from datetime import timedelta

from django.db import models
from django.db.models import Manager
from django.utils import timezone

from aso.scoring import calc_opportunity, classify_keyword, get_targeting_advice


class App(models.Model):
    """
    Represents one of the user's iOS apps.

    Used for organizing keywords into groups — each keyword can
    optionally be associated with an app.

    When added via App Store lookup, track_id stores the iTunes
    numeric ID so we can find the app's rank in search results.
    """

    id: int  # Auto-generated by Django, declared for type checkers
    keywords: Manager[Keyword]

    name = models.CharField(max_length=200)
    bundle_id = models.CharField(
        max_length=200,
        blank=True,
        default="",
        help_text="e.g., com.example.myapp",
    )
    track_id = models.BigIntegerField(
        null=True,
        blank=True,
        unique=True,
        help_text="iTunes trackId — used for rank tracking in search results",
    )
    store_url = models.URLField(
        blank=True,
        default="",
        help_text="App Store URL",
    )
    icon_url = models.URLField(
        blank=True,
        default="",
        help_text="App icon URL from iTunes",
    )
    seller_name = models.CharField(
        max_length=200,
        blank=True,
        default="",
        help_text="Developer/publisher name",
    )
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name


class Keyword(models.Model):
    """
    A keyword being tracked for ASO research.

    Can optionally be linked to an App for categorization.
    """

    id: int  # Auto-generated by Django, declared for type checkers
    results: Manager[SearchResult]

    keyword = models.CharField(max_length=200)
    app = models.ForeignKey(
        App,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="keywords",
    )
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ("keyword", "app")
        ordering = ["-created_at"]

    def __str__(self):
        if self.app:
            return f"{self.keyword} ({self.app.name})"
        return self.keyword


class SearchResult(models.Model):
    """
    Stores the result of a keyword search at a point in time.

    Contains popularity score (from Apple), difficulty score (calculated),
    and the raw competitor data from iTunes Search API.
    """

    id: int  # Auto-generated by Django, declared for type checkers

    keyword = models.ForeignKey(
        Keyword,
        on_delete=models.CASCADE,
        related_name="results",
    )
    popularity_score = models.IntegerField(
        null=True,
        blank=True,
        help_text="5-100 popularity score estimated by RespectASO's internal algorithm.",
    )
    apple_popularity_score = models.IntegerField(
        null=True,
        blank=True,
        help_text=(
            "5-100 granular popularity from Apple Ads at snapshot time "
            "(null when Apple had no value for this keyword+country)."
        ),
    )
    difficulty_score = models.IntegerField(
        help_text="1-100 calculated difficulty score",
    )
    difficulty_breakdown = models.JSONField(
        default=dict,
        help_text="Component scores breakdown",
    )
    competitors_data = models.JSONField(
        default=list,
        help_text="Array of top competitor app dicts from iTunes",
    )
    app_rank = models.IntegerField(
        null=True,
        blank=True,
        help_text="App's 1-indexed rank in top-200 iTunes results (null if not found)",
    )
    country = models.CharField(
        max_length=5,
        default="us",
        help_text="Country code used for this search",
    )
    classification = models.CharField(
        max_length=20,
        default="Moderate",
        help_text="Keyword classification label from classify_keyword()",
    )
    searched_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["-searched_at"]

    def __str__(self):
        return f"{self.keyword.keyword} — {self.searched_at:%Y-%m-%d %H:%M}"

    @classmethod
    def upsert_today(cls, keyword, country, **fields):
        """
        Create or replace today's result for a keyword+country pair.

        If a result already exists for today, delete it and create a fresh one.
        This ensures exactly one data point per keyword per country per day.
        """
        today_start = timezone.now().replace(hour=0, minute=0, second=0, microsecond=0)
        today_end = today_start + timedelta(days=1)
        cls.objects.filter(
            keyword=keyword,
            country=country,
            searched_at__gte=today_start,
            searched_at__lt=today_end,
        ).delete()
        return cls.objects.create(keyword=keyword, country=country, **fields)

    def save(self, *args, **kwargs):
        """Auto-compute classification from the effective popularity on save."""
        self.classification = classify_keyword(
            self.effective_popularity or 0, self.difficulty_score
        )
        super().save(*args, **kwargs)

    def _resolve_popularity_pair(self):
        """(effective, source, is_fallback) per the user's source selection."""
        from .popularity import effective_from_pair, get_popularity_source

        return effective_from_pair(
            self.popularity_score,
            self.apple_popularity_score,
            get_popularity_source(),
        )

    @property
    def effective_popularity(self):
        """The popularity value that feeds all calculations for this row."""
        return self._resolve_popularity_pair()[0]

    @property
    def popularity_source_used(self):
        """"internal" or "apple" — the source of effective_popularity."""
        return self._resolve_popularity_pair()[1]

    @property
    def popularity_is_fallback(self):
        """True when Apple is selected but this row has no Apple value."""
        return self._resolve_popularity_pair()[2]

    @property
    def difficulty_label(self):
        """Human-readable difficulty interpretation."""
        score = self.difficulty_score
        if score <= 15:
            return "Very Easy"
        elif score <= 35:
            return "Easy"
        elif score <= 55:
            return "Moderate"
        elif score <= 75:
            return "Hard"
        elif score <= 90:
            return "Very Hard"
        return "Extreme"

    @property
    def difficulty_color(self):
        """Tailwind color class for the difficulty score."""
        score = self.difficulty_score
        if score <= 15:
            return "text-green-400"
        elif score <= 35:
            return "text-green-300"
        elif score <= 55:
            return "text-yellow-400"
        elif score <= 75:
            return "text-orange-400"
        elif score <= 90:
            return "text-red-400"
        return "text-red-600"

    @property
    def opportunity_score(self):
        """Computed opportunity score from the effective popularity."""
        return calc_opportunity(self.effective_popularity or 0, self.difficulty_score)

    @property
    def targeting_advice(self):
        """Return (icon, label, css_classes, description) for ASO targeting."""
        return get_targeting_advice(self.effective_popularity, self.difficulty_score)

    @property
    def effective_download_estimates(self):
        """Download estimates recomputed from the EFFECTIVE popularity.

        The snapshot stored in difficulty_breakdown was computed with the
        popularity source active at scoring time; recomputing at read time
        (DownloadEstimator is pure, deterministic math) keeps the downloads
        column consistent with the popularity column after a source switch.
        Returns None when this row has no popularity at all.
        """
        effective = self.effective_popularity
        if effective is None:
            return None
        from .services import DownloadEstimator

        return DownloadEstimator().estimate(effective, country=self.country)


class AppleSearchPopularity(models.Model):
    """
    Local lookup table of Apple's granular keyword popularity values.

    Populated by aso.apple_ads.sync from the Apple Ads keyword-planner
    endpoint. One row per (term, country), overwritten by newer fetches.
    Scoring reads this table only (never the network).

    popularity is null when Apple reported no value for the term (below
    Apple's volume threshold) — stored with a timestamp so the sync does
    not re-query known-empty terms on every run.
    """

    id: int  # Auto-generated by Django, declared for type checkers

    term = models.CharField(
        max_length=200,
        help_text="Normalized keyword (lower().strip()).",
    )
    country = models.CharField(
        max_length=5,
        help_text="Storefront country code, lowercase (e.g. 'us').",
    )
    popularity = models.IntegerField(
        null=True,
        blank=True,
        help_text="Granular 5-100 Apple popularity; null = below Apple's threshold.",
    )
    fetched_at = models.DateTimeField(auto_now=True)

    class Meta:
        unique_together = ("term", "country")
        indexes = [models.Index(fields=["term", "country"])]
        verbose_name_plural = "Apple search popularities"

    def __str__(self):
        return f"{self.term} ({self.country}) — {self.popularity}"

    @classmethod
    def lookup(cls, term, country):
        """Return the Apple popularity for a normalized term, or None."""
        return (
            cls.objects.filter(term=term, country=country)
            .values_list("popularity", flat=True)
            .first()
        )

    @classmethod
    def bulk_lookup(cls, terms, country):
        """Return {term: popularity} for the given normalized terms (one query).

        Terms Apple has no row for are absent; terms with a null value map
        to None (both resolve to the internal fallback downstream).
        """
        rows = cls.objects.filter(term__in=list(terms), country=country)
        return dict(rows.values_list("term", "popularity"))
