# Generated by Django 5.2.8 on 2026-02-21 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(help_text='Apple Search Ads Client ID (e.g., SEARCHADS.xxx)', max_length=255)),
                ('team_id', models.CharField(help_text='Apple Search Ads Team ID (e.g., SEARCHADS.xxx)', max_length=255)),
                ('key_id', models.CharField(help_text='Key ID from Apple Ads UI after uploading public key', max_length=255)),
                ('private_key_encrypted', models.TextField(help_text='PEM private key, encrypted at rest')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'API Credential',
                'verbose_name_plural': 'API Credentials',
            },
        ),
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('bundle_id', models.CharField(blank=True, default='', help_text='e.g., com.example.myapp', max_length=200)),
                ('icon_url', models.URLField(blank=True, default='', help_text='Optional icon URL for display')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('app', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='keywords', to='aso.app')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('keyword', 'app')},
            },
        ),
        migrations.CreateModel(
            name='SearchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('popularity_score', models.IntegerField(blank=True, help_text='1-100 from Apple Search Ads. Null if no credentials configured.', null=True)),
                ('difficulty_score', models.IntegerField(help_text='1-100 calculated difficulty score')),
                ('difficulty_breakdown', models.JSONField(default=dict, help_text='Component scores breakdown')),
                ('competitors_data', models.JSONField(default=list, help_text='Array of top competitor app dicts from iTunes')),
                ('country', models.CharField(default='us', help_text='Country code used for this search', max_length=5)),
                ('searched_at', models.DateTimeField(auto_now_add=True)),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='aso.keyword')),
            ],
            options={
                'ordering': ['-searched_at'],
            },
        ),
    ]
