# Generated by Django 5.1.15 on 2026-02-21 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aso', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='seller_name',
            field=models.CharField(blank=True, default='', help_text='Developer/publisher name', max_length=200),
        ),
        migrations.AddField(
            model_name='app',
            name='store_url',
            field=models.URLField(blank=True, default='', help_text='App Store URL'),
        ),
        migrations.AddField(
            model_name='app',
            name='track_id',
            field=models.BigIntegerField(blank=True, help_text='iTunes trackId — used for rank tracking in search results', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='app',
            name='icon_url',
            field=models.URLField(blank=True, default='', help_text='App icon URL from iTunes'),
        ),
    ]
