# Generated by Django 5.2.8 on 2026-02-21 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aso', '0002_app_seller_name_app_store_url_app_track_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchresult',
            name='app_rank',
            field=models.IntegerField(blank=True, help_text="App's 1-indexed rank in top-200 iTunes results (null if not found)", null=True),
        ),
    ]
