# Generated by Django 5.2.8 on 2026-02-21 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aso', '0003_searchresult_app_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='apicredential',
            name='org_id',
            field=models.CharField(blank=True, default='', help_text='Apple Search Ads Org ID (required for keyword popularity)', max_length=255),
        ),
    ]
