# Generated by Django 5.2.8 on 2026-02-23 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aso', '0005_delete_apicredential'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchresult',
            name='popularity_score',
            field=models.IntegerField(blank=True, help_text='1-100 estimated popularity score.', null=True),
        ),
    ]
