# Generated by Django 5.1.15 on 2026-04-03 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aso', '0006_alter_searchresult_popularity_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchresult',
            name='classification',
            field=models.CharField(default='Moderate', help_text='Keyword classification label from classify_keyword()', max_length=20),
        ),
    ]
