# Generated by Django 5.1.15 on 2026-04-03 21:30

from django.db import migrations


def backfill_classification(apps, schema_editor):
    """Backfill classification for all existing SearchResult rows."""
    # Import scoring at runtime to avoid AppRegistryNotReady
    from aso.scoring import classify_keyword

    SearchResult = apps.get_model("aso", "SearchResult")
    for sr in SearchResult.objects.all().iterator():
        label = classify_keyword(sr.popularity_score or 0, sr.difficulty_score)
        if sr.classification != label:
            sr.classification = label
            sr.save(update_fields=["classification"])


class Migration(migrations.Migration):

    dependencies = [
        ('aso', '0007_add_classification_field'),
    ]

    operations = [
        migrations.RunPython(backfill_classification, migrations.RunPython.noop),
    ]
