# Generated by Django 5.1.15 on 2026-04-02 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aso', '0008_backfill_classification'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrendSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('google_trends', 'Google Trends'), ('x_twitter', 'X / Twitter'), ('reddit', 'Reddit'), ('product_hunt', 'Product Hunt'), ('hacker_news', 'Hacker News'), ('gdelt_news', 'GDELT News'), ('wikipedia', 'Wikipedia Pageviews'), ('youtube', 'YouTube'), ('app_store', 'App Store Native'), ('tiktok', 'TikTok'), ('bluesky', 'Bluesky'), ('mastodon', 'Mastodon'), ('github', 'GitHub Trending'), ('steam', 'Steam'), ('podcast_index', 'Podcast Index'), ('newsapi', 'NewsAPI'), ('paid_aso', 'Paid ASO Providers')], max_length=50)),
                ('keyword', models.CharField(max_length=500)),
                ('raw_volume', models.FloatField(blank=True, help_text='Source-specific metric (views, mentions, interest score)', null=True)),
                ('normalized_score', models.FloatField(blank=True, help_text='0.0-1.0 normalized intensity', null=True)),
                ('country', models.CharField(default='us', max_length=5)),
                ('metadata', models.JSONField(default=dict, help_text='Source-specific extra data (method, related queries, etc.)')),
                ('first_seen_at', models.DateTimeField(help_text='UTC: when this keyword FIRST appeared in ANY source')),
                ('collected_at', models.DateTimeField(help_text='UTC: when this data point was collected')),
                ('date_stamp', models.DateField(help_text='UTC date for daily deduplication/aggregation')),
            ],
            options={
                'ordering': ['-collected_at'],
                'indexes': [models.Index(fields=['keyword'], name='idx_trendsignal_keyword'), models.Index(fields=['first_seen_at'], name='idx_trendsignal_first_seen'), models.Index(fields=['source', 'date_stamp'], name='idx_trendsignal_src_date')],
                'unique_together': {('source', 'keyword', 'country', 'date_stamp')},
            },
        ),
    ]
