# Generated by Django 5.1.15 on 2026-07-19 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aso', '0008_backfill_classification'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchresult',
            name='apple_popularity_score',
            field=models.IntegerField(blank=True, help_text='5-100 granular popularity from Apple Ads at snapshot time (null when Apple had no value for this keyword+country).', null=True),
        ),
        migrations.AlterField(
            model_name='searchresult',
            name='popularity_score',
            field=models.IntegerField(blank=True, help_text="5-100 popularity score estimated by RespectASO's internal algorithm.", null=True),
        ),
        migrations.CreateModel(
            name='AppleSearchPopularity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(help_text='Normalized keyword (lower().strip()).', max_length=200)),
                ('country', models.CharField(help_text="Storefront country code, lowercase (e.g. 'us').", max_length=5)),
                ('popularity', models.IntegerField(blank=True, help_text="Granular 5-100 Apple popularity; null = below Apple's threshold.", null=True)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Apple search popularities',
                'indexes': [models.Index(fields=['term', 'country'], name='aso_applese_term_459fd3_idx')],
                'unique_together': {('term', 'country')},
            },
        ),
    ]
