# Generated by Django 5.1.15 on 2026-08-17 09:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aso', '0009_searchresult_apple_popularity_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applesearchpopularity',
            name='popularity',
            field=models.IntegerField(blank=True, help_text="Apple searchPopularity1to100 (observed floor ~40); null = absent from Apple's top search terms for this storefront.", null=True),
        ),
        migrations.CreateModel(
            name='AppleTopTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(help_text='Normalized search term (lower().strip()).', max_length=200)),
                ('country', models.CharField(help_text="Storefront country code, lowercase (e.g. 'us').", max_length=5)),
                ('genre', models.CharField(help_text="Apple genre value as returned by the API (e.g. 'BUSINESS').", max_length=100)),
                ('week', models.DateField(help_text='Sunday starting the Sun-Sat week this snapshot covers.')),
                ('rank_in_genre', models.IntegerField(help_text='Rank by search volume within country+genre (1 = highest).')),
                ('popularity_in_genre', models.SmallIntegerField(help_text='1-100 popularity within the genre for this storefront.')),
                ('popularity', models.SmallIntegerField(help_text='searchPopularity1to100: 1-100 across all genres in the storefront (observed floor ~40). Feeds scoring.')),
                ('popularity_tier', models.SmallIntegerField(help_text='1-5 scale matching the Apple Ads Campaign Management UI.')),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'indexes': [models.Index(fields=['country', 'week'], name='aso_appleto_country_355dc6_idx'), models.Index(fields=['term', 'country', 'week'], name='aso_appleto_term_21e37d_idx'), models.Index(fields=['country', 'genre', 'week', 'rank_in_genre'], name='aso_appleto_country_1b3d8c_idx')],
                'unique_together': {('term', 'country', 'genre', 'week')},
            },
        ),
        migrations.CreateModel(
            name='AppleImpressionShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(help_text='Storefront country code, lowercase.', max_length=5)),
                ('search_term', models.CharField(help_text='Normalized search term the ads served on.', max_length=200)),
                ('week', models.DateField(help_text='Sunday starting the Sun-Sat week this row covers.')),
                ('low_share', models.FloatField(help_text='Lower bound of impression share, 0..1. Apple reports exact single-digit values between 1-90% and the band 91-100%.')),
                ('high_share', models.FloatField(help_text='Upper bound of impression share, 0..1.')),
                ('rank', models.IntegerField(blank=True, help_text="App's impression-share rank on the term (1 = highest).", null=True)),
                ('popularity_tier', models.SmallIntegerField(blank=True, help_text="Apple's 1-5 search popularity for the term.", null=True)),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impression_shares', to='aso.app')),
            ],
            options={
                'indexes': [models.Index(fields=['app', 'week'], name='aso_appleim_app_id_f4c292_idx')],
                'unique_together': {('app', 'country', 'search_term', 'week')},
            },
        ),
    ]
