# Generated by Django 5.1.15 on 2026-08-17 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aso', '0010_alter_applesearchpopularity_popularity_appletopterm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchresult',
            name='inferred_genre',
            field=models.CharField(blank=True, default='', help_text="Apple genre bucket inferred from this snapshot's competitors (aso.apple_ads.genres). Drives the genre-aware fallback cap under the Apple source; empty = uninferred (global floor).", max_length=100),
        ),
    ]
