# Generated by Django 5.1.15 on 2026-08-17 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aso', '0011_searchresult_inferred_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchresult',
            name='apple_popularity_score',
            field=models.IntegerField(blank=True, help_text="Apple's official searchPopularity1to100 at snapshot time (null when the keyword was not among Apple's top terms).", null=True),
        ),
        migrations.AlterField(
            model_name='searchresult',
            name='popularity_score',
            field=models.IntegerField(blank=True, help_text="RespectASO's estimate (1-100, calibrated to Apple's official popularity scale - estimate v2).", null=True),
        ),
    ]
