# Generated by Django 5.1.15 on 2026-09-04 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aso', '0012_alter_searchresult_apple_popularity_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeywordSearchJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countries', models.JSONField(default=list)),
                ('keywords', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('paused', 'Paused'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=12)),
                ('queue_rank', models.IntegerField(blank=True, null=True)),
                ('auto_resume', models.BooleanField(default=False)),
                ('yielded_for_feature', models.CharField(blank=True, default='', max_length=32)),
                ('yielded_for_id', models.IntegerField(blank=True, null=True)),
                ('yielded_for_label', models.CharField(blank=True, default='', max_length=220)),
                ('next_index', models.PositiveIntegerField(default=0)),
                ('done_count', models.PositiveIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('skipped_items', models.JSONField(default=list)),
                ('failed_items', models.JSONField(default=list)),
                ('current_pair', models.CharField(blank=True, default='', max_length=220)),
                ('progress_message', models.CharField(blank=True, default='', max_length=200)),
                ('error_message', models.TextField(blank=True, default='')),
                ('throttle_state', models.CharField(choices=[('normal', 'Normal'), ('slowed_down', 'Slowed down'), ('paused', 'Paused by throttling'), ('cooldown', 'Cooling down')], default='normal', max_length=16)),
                ('seconds_per_pair', models.FloatField(blank=True, null=True)),
                ('elapsed_seconds', models.FloatField(default=0)),
                ('acknowledged', models.BooleanField(default=False)),
                ('restart_resumes', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('app', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_jobs', to='aso.app')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
