# Generated by Django 5.1.15 on 2026-09-22 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aso', '0013_keyword_search_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpportunityScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=200)),
                ('countries', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('paused', 'Paused'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=12)),
                ('queue_rank', models.IntegerField(blank=True, null=True)),
                ('auto_resume', models.BooleanField(default=False)),
                ('yielded_for_feature', models.CharField(blank=True, default='', max_length=32)),
                ('yielded_for_id', models.IntegerField(blank=True, null=True)),
                ('yielded_for_label', models.CharField(blank=True, default='', max_length=220)),
                ('next_index', models.PositiveIntegerField(default=0)),
                ('done_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('failed_items', models.JSONField(default=list)),
                ('current_country', models.CharField(blank=True, default='', max_length=5)),
                ('progress_message', models.CharField(blank=True, default='', max_length=200)),
                ('error_message', models.TextField(blank=True, default='')),
                ('throttle_state', models.CharField(choices=[('normal', 'Normal'), ('slowed_down', 'Slowed down'), ('paused', 'Paused by throttling'), ('cooldown', 'Cooling down')], default='normal', max_length=16)),
                ('seconds_per_country', models.FloatField(blank=True, null=True)),
                ('elapsed_seconds', models.FloatField(default=0)),
                ('heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged', models.BooleanField(default=False)),
                ('restart_resumes', models.PositiveIntegerField(default=0)),
                ('saved_count', models.PositiveIntegerField(default=0)),
                ('origin', models.CharField(choices=[('web', 'Web'), ('mcp', 'MCP')], default='web', max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('app', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunity_scans', to='aso.app')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OpportunityScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=5)),
                ('order_index', models.PositiveIntegerField()),
                ('keyword_text', models.CharField(max_length=200)),
                ('popularity_score', models.IntegerField(blank=True, null=True)),
                ('apple_popularity_score', models.IntegerField(blank=True, null=True)),
                ('inferred_genre', models.CharField(blank=True, default='', max_length=80)),
                ('difficulty_score', models.IntegerField(default=0)),
                ('app_rank', models.IntegerField(blank=True, null=True)),
                ('competitor_count', models.PositiveIntegerField(default=0)),
                ('top_competitor', models.CharField(blank=True, default='', max_length=255)),
                ('top_ratings', models.PositiveIntegerField(default=0)),
                ('difficulty_breakdown', models.JSONField(default=dict)),
                ('competitors_data', models.JSONField(default=list)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='aso.opportunityscan')),
            ],
            options={
                'ordering': ['order_index'],
                'indexes': [models.Index(fields=['scan', 'order_index'], name='aso_opportu_scan_id_f65d73_idx')],
                'unique_together': {('scan', 'country')},
            },
        ),
    ]
