# Generated by Django 5.1.15 on 2026-09-22 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aso', '0014_opportunityscan_opportunityscanresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='ratings_by_storefront',
            field=models.JSONField(blank=True, default=dict, help_text="This app's rating count in each storefront, as last read from the App Store: {code: {count, checked_at}}. Written only by aso/app_strength.py; the opportunity score reads it."),
        ),
    ]
