# Generated by Django 5.1.15 on 2026-09-23 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aso', '0016_store_profiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchresult',
            name='classification',
            field=models.CharField(default='Low Volume', help_text='Keyword classification label from classify_keyword()', max_length=20),
        ),
    ]
