# Generated by Django 5.1.15 on 2026-09-27 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aso', '0017_classification_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='track_id',
            field=models.BigIntegerField(blank=True, help_text='iTunes trackId, used for rank tracking in search results', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='searchresult',
            name='popularity_score',
            field=models.IntegerField(blank=True, help_text="RespectASO's estimate (1-100, calibrated to Apple's official popularity scale, estimate v2).", null=True),
        ),
    ]
