# Generated by Django 5.1.15 on 2026-09-29 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aso', '0019_historyrevision'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeywordTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='aso.keyword')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='aso_keyword_name_80645e_idx')],
                'unique_together': {('keyword', 'name')},
            },
        ),
    ]
