# Generated by Django 5.1.15 on 2026-09-30 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = (
        ('aso', '0021_keywordlabel'),
    )

    operations = (
        migrations.CreateModel(
            name='KeywordDayRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(help_text='The keyword as aso.popularity.normalize_term writes it.', max_length=200)),
                ('country', models.CharField(help_text='Storefront code, lower case.', max_length=5)),
                ('day', models.DateField(help_text="The reader's day the search belongs to (aso/local_day.py).")),
                ('ranked_ids', models.JSONField(default=list, help_text="Every app's trackId in Apple's order, up to 200.")),
                ('result_count', models.IntegerField(default=0, help_text='How many apps the search returned.')),
                ('competitors', models.JSONField(default=list, help_text='The first 25 apps as full app dicts; emptied once the day is over.')),
                ('fetched_at', models.DateTimeField(help_text='When Apple answered.')),
            ],
            options={
                'indexes': [models.Index(fields=['day'], name='keyword_day_read_day')],
                'constraints': [models.UniqueConstraint(fields=('term', 'country', 'day'), name='unique_keyword_day_read')],
            },
        ),
    )
