# Generated by Django 5.1.15 on 2026-10-03 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aso', '0022_keyworddayread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='icon_url',
            field=models.URLField(blank=True, default='', help_text="App icon URL from iTunes. 500 characters, as the Rival Tracker's icon fields.", max_length=500),
        ),
    ]
