# Generated by Django 5.1.15 on 2026-10-07 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aso', '0023_app_icon_url_500'),
    ]

    operations = [
        migrations.AddField(
            model_name='keywordsearchjob',
            name='run_owner',
            field=models.CharField(blank=True, db_default='', default='', max_length=64),
        ),
        migrations.AddField(
            model_name='opportunityscan',
            name='run_owner',
            field=models.CharField(blank=True, db_default='', default='', max_length=64),
        ),
    ]
